#! /bin/sh
rm -rf ../my

put=500
drop=500

beg1=1
end1=`echo "$beg1+$put" | bc`
beg2=1001
end2=`echo "$beg2+$drop" | bc`

make

beg=$(date +%s.%N)
./pear $beg1 $end1 $beg2 $end2
end=$(date +%s.%N)

res=`echo "$end-$beg" | bc`
gprof pear ../my/gmon.out -p > pinfo
sed -n -e 4,19p -s pinfo
rm ../my/gmon.out pinfo

echo $res
